### ISSUE TITLE
[Q&A] How to uninstall `busybox`?

### ISSUE THREAD

**Issue by UltraStudioLTD** [Magisk-Modules-Alt-Repo/BuiltIn-BusyBox#2]
I have installed this module and after noticing that `RootBeer Sample`  detects root via BusyBox checking I decided to uninstall it but unfortunately this module doesn't include BusyBox removal and I can't manually remove BusyBox.
So question: How can I remove `busybox` from /system/xbin?

**Comment by UltraStudioLTD** [comment]
I disabled every module temporarily and manually removed `busybox` without any problem.

**Comment by zgfg** [comment]
Uninstall as any other module - there is an option in the Magisk app

If you use Magisk, please learn minimal basic things like about Magisk app and how to use it

**Comment by zgfg** [comment]
Besides, from checkers like RootBeer (like from the real 'banking' and similar apps), you have to hide the root

Put RootBeer to DenyList and it won't find Magisk neither the BusyBox:
![Screenshot_2023-01-30-21-49-45-750_com scottyab rootbeer sample](https://user-images.githubusercontent.com/51943147/215591909-ed0292f9-102c-4345-9d59-5d988cb2f377.jpg)

**Comment by UltraStudioLTD** [comment]
> Uninstall as any other module - there is an option in the **Magisk** app

Reason why I asked is that even after uninstallation **busybox** binary remains in installation path. Reason is lack of removal script which is called **uninstall.sh** which should include functionality to completely remove modifications caused by module.
See [magisk modules](https://topjohnwu.github.io/Magisk/guides.html#magisk-modules) to understand what I mean.

> If using **Magisk**, please be familiar with minimal basic things like how to use the **Magisk** app

Care to explain why do you think that I am not familiar with **Magisk** manager and it's module system?

**Comment by UltraStudioLTD** [comment]
> Besides, from the checkers like RootBeer Sample or Fresh, Oprek, TB-Checker, etc (like from any real 'banking' and similar apps), you have to hide root
> 
> Put RootBeer (Oprek, TB-Checker) ![Screenshot_2023-01-30-22-38-53-728_com godevelopers OprekCek](https://user-images.githubusercontent.com/51943147/215602001-b7198c05-9f77-40af-98aa-0a2b7fceda1f.jpg) ![Screenshot_2023-01-30-22-40-36-180_krypton tbsafetychecker](https://user-images.githubusercontent.com/51943147/215602024-464dee57-85a7-4e34-83c2-0bd384b67169.jpg) to DenyList and it won't find Magisk neither the BusyBox: ![Screenshot_2023-01-30-21-49-45-750_com scottyab rootbeer sample](https://user-images.githubusercontent.com/51943147/215591909-ed0292f9-102c-4345-9d59-5d988cb2f377.jpg) ![Screenshot_2023-01-30-21-57-32-392_com kimchangyoun rootbeerFresh sample](https://user-images.githubusercontent.com/51943147/215594066-cf964fb0-c749-4acd-864d-6db2946c34f7.jpg)

I know that but adding to **Magisk**'s **Deny List** doesn't have any effect because module is installed in **/system/(x)bin/** directory which every application can easily check whether it contains **busybox** binary or not.

**Comment by zgfg** [comment]
Uninstall from Magisk app and reboot (phone must be rebooted when modules are uninstallwd)
Magisk will remove the module's folder
/data/adb/modules/BuiltIn-BusyBox

and Magisk will no more mount BusyBox applets from 
/data/adb/modules/BuiltIn-BusyBox/system/xbin
to
/system/xbin

This is the point with Sysremless modules - this module itself does not change anything else, anywhere - it only installs to that folder and when module is uninstalled, Magisk deletes that folder and there is nothing else to be cleaned by uninstall.sh script, since the module did not leave its garbage anywhere else

If you see
/data/adb/magisk/BusyBox

or
/data/unencrypted/MAGISKBIN/BusyBox

That BB was not was not installed by the modele - that BB was installed as part of Magisk installation itself
(second path above is BusyBox installed by Magisk Delta - Delta installs to
/data/unencrypted/MAGISKBIN
and links to
/data/adb/magisk
